e=set()

n=int(input("enter num : "))
e.add(int(n))
n=int(input("enter num : "))
e.add(int(n))
n=int(input("enter num : "))
e.add(int(n))
n=int(input("enter num : "))
e.add(int(n))
n=int(input("enter num : "))
e.add(int(n))
n=int(input("enter num : "))
e.add(int(n))
n=int(input("enter num : "))
e.add(int(n))
n=int(input("enter num : "))
e.add(int(n))

print(e)